AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false